/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/dpickler/Work/neurobotics/catkin_ws/src/neuro_recv/msg/dish_state.msg
 *
 */


#ifndef NEURO_RECV_MESSAGE_DISH_STATE_H
#define NEURO_RECV_MESSAGE_DISH_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neuro_recv
{
template <class ContainerAllocator>
struct dish_state_
{
  typedef dish_state_<ContainerAllocator> Type;

  dish_state_()
    : header()
    , samples()
    , last_dish(false)  {
      samples.assign(0.0);
  }
  dish_state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , samples()
    , last_dish(false)  {
      samples.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 60>  _samples_type;
  _samples_type samples;

   typedef uint8_t _last_dish_type;
  _last_dish_type last_dish;




  typedef boost::shared_ptr< ::neuro_recv::dish_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neuro_recv::dish_state_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct dish_state_

typedef ::neuro_recv::dish_state_<std::allocator<void> > dish_state;

typedef boost::shared_ptr< ::neuro_recv::dish_state > dish_statePtr;
typedef boost::shared_ptr< ::neuro_recv::dish_state const> dish_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neuro_recv::dish_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neuro_recv::dish_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neuro_recv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'neuro_recv': ['/home/dpickler/Work/neurobotics/catkin_ws/src/neuro_recv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neuro_recv::dish_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neuro_recv::dish_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuro_recv::dish_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuro_recv::dish_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuro_recv::dish_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuro_recv::dish_state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neuro_recv::dish_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c08ea80d278c864525005be19edfdf2f";
  }

  static const char* value(const ::neuro_recv::dish_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc08ea80d278c8645ULL;
  static const uint64_t static_value2 = 0x25005be19edfdf2fULL;
};

template<class ContainerAllocator>
struct DataType< ::neuro_recv::dish_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neuro_recv/dish_state";
  }

  static const char* value(const ::neuro_recv::dish_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neuro_recv::dish_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Dish state message\n\
Header header\n\
float64[60] samples\n\
bool last_dish\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::neuro_recv::dish_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neuro_recv::dish_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.samples);
      stream.next(m.last_dish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct dish_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neuro_recv::dish_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neuro_recv::dish_state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "samples[]" << std::endl;
    for (size_t i = 0; i < v.samples.size(); ++i)
    {
      s << indent << "  samples[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.samples[i]);
    }
    s << indent << "last_dish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.last_dish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEURO_RECV_MESSAGE_DISH_STATE_H
