/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/dpickler/Work/neurobotics/catkin_ws/src/img_slicer/srv/ImageSlicer.srv
 *
 */


#ifndef IMG_SLICER_MESSAGE_IMAGESLICERRESPONSE_H
#define IMG_SLICER_MESSAGE_IMAGESLICERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace img_slicer
{
template <class ContainerAllocator>
struct ImageSlicerResponse_
{
  typedef ImageSlicerResponse_<ContainerAllocator> Type;

  ImageSlicerResponse_()
    : pixelCount()  {
    }
  ImageSlicerResponse_(const ContainerAllocator& _alloc)
    : pixelCount(_alloc)  {
    }



   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _pixelCount_type;
  _pixelCount_type pixelCount;




  typedef boost::shared_ptr< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ImageSlicerResponse_

typedef ::img_slicer::ImageSlicerResponse_<std::allocator<void> > ImageSlicerResponse;

typedef boost::shared_ptr< ::img_slicer::ImageSlicerResponse > ImageSlicerResponsePtr;
typedef boost::shared_ptr< ::img_slicer::ImageSlicerResponse const> ImageSlicerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::img_slicer::ImageSlicerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace img_slicer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c962d0921f665af4061271577e235ba";
  }

  static const char* value(const ::img_slicer::ImageSlicerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c962d0921f665afULL;
  static const uint64_t static_value2 = 0x4061271577e235baULL;
};

template<class ContainerAllocator>
struct DataType< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "img_slicer/ImageSlicerResponse";
  }

  static const char* value(const ::img_slicer::ImageSlicerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64[] pixelCount\n\
";
  }

  static const char* value(const ::img_slicer::ImageSlicerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pixelCount);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ImageSlicerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::img_slicer::ImageSlicerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::img_slicer::ImageSlicerResponse_<ContainerAllocator>& v)
  {
    s << indent << "pixelCount[]" << std::endl;
    for (size_t i = 0; i < v.pixelCount.size(); ++i)
    {
      s << indent << "  pixelCount[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.pixelCount[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMG_SLICER_MESSAGE_IMAGESLICERRESPONSE_H
