/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/dpickler/Work/neurobotics/catkin_ws/src/time_server/srv/time_srv.srv
 *
 */


#ifndef TIME_SERVER_MESSAGE_TIME_SRVREQUEST_H
#define TIME_SERVER_MESSAGE_TIME_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace time_server
{
template <class ContainerAllocator>
struct time_srvRequest_
{
  typedef time_srvRequest_<ContainerAllocator> Type;

  time_srvRequest_()
    : target()  {
    }
  time_srvRequest_(const ContainerAllocator& _alloc)
    : target()  {
    }



   typedef ros::Time _target_type;
  _target_type target;




  typedef boost::shared_ptr< ::time_server::time_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::time_server::time_srvRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct time_srvRequest_

typedef ::time_server::time_srvRequest_<std::allocator<void> > time_srvRequest;

typedef boost::shared_ptr< ::time_server::time_srvRequest > time_srvRequestPtr;
typedef boost::shared_ptr< ::time_server::time_srvRequest const> time_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::time_server::time_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::time_server::time_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace time_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::time_server::time_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::time_server::time_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::time_server::time_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::time_server::time_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::time_server::time_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::time_server::time_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::time_server::time_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db8caddc76616a835ffc8fba07846605";
  }

  static const char* value(const ::time_server::time_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb8caddc76616a83ULL;
  static const uint64_t static_value2 = 0x5ffc8fba07846605ULL;
};

template<class ContainerAllocator>
struct DataType< ::time_server::time_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time_server/time_srvRequest";
  }

  static const char* value(const ::time_server::time_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::time_server::time_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
time target\n\
";
  }

  static const char* value(const ::time_server::time_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::time_server::time_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct time_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::time_server::time_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::time_server::time_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIME_SERVER_MESSAGE_TIME_SRVREQUEST_H
