/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/dpickler/Work/neurobotics/catkin_ws/src/time_server/srv/time_srv.srv
 *
 */


#ifndef TIME_SERVER_MESSAGE_TIME_SRV_H
#define TIME_SERVER_MESSAGE_TIME_SRV_H

#include <ros/service_traits.h>


#include <time_server/time_srvRequest.h>
#include <time_server/time_srvResponse.h>


namespace time_server
{

struct time_srv
{

typedef time_srvRequest Request;
typedef time_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct time_srv
} // namespace time_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::time_server::time_srv > {
  static const char* value()
  {
    return "538088de2280801645bd68bcaa6d0173";
  }

  static const char* value(const ::time_server::time_srv&) { return value(); }
};

template<>
struct DataType< ::time_server::time_srv > {
  static const char* value()
  {
    return "time_server/time_srv";
  }

  static const char* value(const ::time_server::time_srv&) { return value(); }
};


// service_traits::MD5Sum< ::time_server::time_srvRequest> should match 
// service_traits::MD5Sum< ::time_server::time_srv > 
template<>
struct MD5Sum< ::time_server::time_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::time_server::time_srv >::value();
  }
  static const char* value(const ::time_server::time_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::time_server::time_srvRequest> should match 
// service_traits::DataType< ::time_server::time_srv > 
template<>
struct DataType< ::time_server::time_srvRequest>
{
  static const char* value()
  {
    return DataType< ::time_server::time_srv >::value();
  }
  static const char* value(const ::time_server::time_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::time_server::time_srvResponse> should match 
// service_traits::MD5Sum< ::time_server::time_srv > 
template<>
struct MD5Sum< ::time_server::time_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::time_server::time_srv >::value();
  }
  static const char* value(const ::time_server::time_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::time_server::time_srvResponse> should match 
// service_traits::DataType< ::time_server::time_srv > 
template<>
struct DataType< ::time_server::time_srvResponse>
{
  static const char* value()
  {
    return DataType< ::time_server::time_srv >::value();
  }
  static const char* value(const ::time_server::time_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIME_SERVER_MESSAGE_TIME_SRV_H
