/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/dpickler/Work/neurobotics/catkin_ws/src/burst_calc/msg/ranges.msg
 *
 */


#ifndef BURST_CALC_MESSAGE_RANGES_H
#define BURST_CALC_MESSAGE_RANGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace burst_calc
{
template <class ContainerAllocator>
struct ranges_
{
  typedef ranges_<ContainerAllocator> Type;

  ranges_()
    : header()
    , baselines()
    , thresholds()
    , min_volts()
    , max_volts()  {
      baselines.assign(0.0);

      thresholds.assign(0.0);

      min_volts.assign(0.0);

      max_volts.assign(0.0);
  }
  ranges_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , baselines()
    , thresholds()
    , min_volts()
    , max_volts()  {
      baselines.assign(0.0);

      thresholds.assign(0.0);

      min_volts.assign(0.0);

      max_volts.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 60>  _baselines_type;
  _baselines_type baselines;

   typedef boost::array<double, 60>  _thresholds_type;
  _thresholds_type thresholds;

   typedef boost::array<double, 60>  _min_volts_type;
  _min_volts_type min_volts;

   typedef boost::array<double, 60>  _max_volts_type;
  _max_volts_type max_volts;




  typedef boost::shared_ptr< ::burst_calc::ranges_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::burst_calc::ranges_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ranges_

typedef ::burst_calc::ranges_<std::allocator<void> > ranges;

typedef boost::shared_ptr< ::burst_calc::ranges > rangesPtr;
typedef boost::shared_ptr< ::burst_calc::ranges const> rangesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::burst_calc::ranges_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::burst_calc::ranges_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace burst_calc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'burst_calc': ['/home/dpickler/Work/neurobotics/catkin_ws/src/burst_calc/msg'], 'neuro_recv': ['/home/dpickler/Work/neurobotics/catkin_ws/src/neuro_recv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::burst_calc::ranges_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::burst_calc::ranges_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burst_calc::ranges_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burst_calc::ranges_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burst_calc::ranges_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burst_calc::ranges_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::burst_calc::ranges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4760225b9a5eb17caa1ce5a89eca2bc9";
  }

  static const char* value(const ::burst_calc::ranges_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4760225b9a5eb17cULL;
  static const uint64_t static_value2 = 0xaa1ce5a89eca2bc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::burst_calc::ranges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "burst_calc/ranges";
  }

  static const char* value(const ::burst_calc::ranges_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::burst_calc::ranges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ranges message\n\
Header header\n\
float64[60] baselines\n\
float64[60] thresholds\n\
float64[60] min_volts\n\
float64[60] max_volts\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::burst_calc::ranges_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::burst_calc::ranges_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.baselines);
      stream.next(m.thresholds);
      stream.next(m.min_volts);
      stream.next(m.max_volts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ranges_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::burst_calc::ranges_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::burst_calc::ranges_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "baselines[]" << std::endl;
    for (size_t i = 0; i < v.baselines.size(); ++i)
    {
      s << indent << "  baselines[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.baselines[i]);
    }
    s << indent << "thresholds[]" << std::endl;
    for (size_t i = 0; i < v.thresholds.size(); ++i)
    {
      s << indent << "  thresholds[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.thresholds[i]);
    }
    s << indent << "min_volts[]" << std::endl;
    for (size_t i = 0; i < v.min_volts.size(); ++i)
    {
      s << indent << "  min_volts[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.min_volts[i]);
    }
    s << indent << "max_volts[]" << std::endl;
    for (size_t i = 0; i < v.max_volts.size(); ++i)
    {
      s << indent << "  max_volts[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.max_volts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BURST_CALC_MESSAGE_RANGES_H
